version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    command: irb
    # command: sh -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b 0.0.0.0"
    restart: always
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    restart: always

